development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql2
  database: <%= Auth::Config.config['production_database'] %>
  username: <%= Auth::Config.config['production_username'] %>
  password: <%= Auth::Config.config['production_password'] %>
  host: <%= Auth::Config.config['production_host'] %>
  port: <%= Auth::Config.config['production_port'] %>
